import "./globals.css";
import Header from "@/components/ui/Header";
import Providers from "./provider";

export const metadata = {
  title: "QWERO - NFT Market Place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="font-sans">
        <Header />
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
